language: go
go:
- 1.13.x
before_install:
- go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
- go get github.com/mitchellh/gox
install:
- 
script:
- go get -t -v ./...
- diff -u <(echo -n) <(gofmt -d .)
- gox -os="linux" -arch="386 amd64"
- goversioninfo -icon=./images/app.ico
- env GOOS=windows GOARCH=amd64 go build -o nitr_windows_amd64.exe
- env GOOS=windows GOARCH=386 go build -o nitr_windows_386.exe

deploy:
  edge: true
  provider: releases
  api_key: $GITHUB_TOKEN
  on:
    repo: bitcav/nitr
    branches:    
      only:      
      - master 
  skip_cleanup: true
  file:
  - nitr_windows_amd64.exe
  - nitr_windows_386.exe
  - nitr_linux_amd64
  - nitr_linux_386
  draft: true

