language: go
go:
- 1.13.x
before_install:
- go get github.com/mitchellh/gox
install:
- 
script:
- go get -t -v ./...
- diff -u <(echo -n) <(gofmt -d .)
- gox -os="linux windows" -arch="amd64"
deploy:
  edge: true
  provider: releases
  api_key: $GITHUB_TOKEN
  on:
    repo: juanhuttemann/nitr-agent
    branches:    
      only:      
          - master 
  skip_cleanup: true
  file:
  - nitr-agent_windows_amd64.exe
  - nitr-agent_linux_amd64
  draft: true

