language: go
go:
- 1.13.x
- master
before_install:
- go get github.com/mitchellh/gox
install:
- 
script:
- go get -t -v ./...
- diff -u <(echo -n) <(gofmt -d .)
- gox -os="linux windows" -arch="amd64" -output="nitr-agent.." -ldflags "-X main.Rev=`git
  rev-parse --short HEAD`" -verbose ./...
deploy:
  edge: true
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file:
  - nitr-agent.windows.amd64.exe
  - nitr-agent.linux.amd64

