apiVersion: apps/v1
kind: DaemonSet
metadata:
  # 部署名字
  name: nitr
spec:
  #replicas: 2
  # 用来查找关联的 Pod，所有标签都匹配才行
  selector:
    matchLabels:
      app: nitr
  # 定义 Pod 相关数据
  template:
    metadata:
      labels:
        app: nitr
    spec:
      # 定义容器，可以多个
      containers:
        - name: nitr # 容器名字
          image: 121.41.57.216:5000/my_nitr:v0.6 # 镜像
